version: '3.5'
services:
  app_2:
    container_name: app_2
    build: .
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    expose:
      - 5000
    links:
      - elastic_2
    depends_on:
      - elastic_2
    restart: always
    env_file:
      - .env

  elastic_2:
    image: elasticsearch:8.10.2
    container_name: elastic_2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    restart: always
    volumes:
      - elastic_2_volume:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    expose:
      - 9200

  kibana_2:
    image: kibana:8.10.2
    container_name: kibana_2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    depends_on:
      - elastic_2
    restart: always
    env_file:
      - .env

volumes:
  elastic_2_volume:

networks:
  default:
    name: nginx_proxy
    external: true
