version: '3.5'
services:
  app_2:
    container_name: app_2
    build: .
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    links:
      - elastic_2
    networks:
      - net_2
    depends_on:
      - elastic_2
    restart: always
    env_file:
      - .env

  elastic_2:
    image: elasticsearch:8.11.1
    container_name: elastic_2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    restart: always
    volumes:
      - elastic_2_volume:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    networks:
      - net_2

  kibana_2:
    image: kibana:8.11.1
    container_name: kibana_2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - net_2
    depends_on:
      - elastic_2
    restart: always
    env_file:
      - .env

  nginx_2:
    image: nginx:1.25.1-alpine
    container_name: nginx_2
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - net_2
    depends_on:
      - elastic_2
    restart: always
    env_file:
      - .env

networks:
  net_2:

volumes:
  elastic_2_volume: